# GameManager.gd
extends Node

# Add these variables to GameManager.gd:
var selected_towers: Array = []


# Add tower_select to your scene map:
const SCENES = {
	"login":        "res://scenes/login/Login.tscn",
	"main_menu":    "res://scenes/main_menu/MainMenu.tscn",
	"academy":      "res://scenes/academy/Academy.tscn",
	"campaign":     "res://scenes/campaign/level_select/LevelSelect.tscn",
	"placement_quiz": "res://scenes/placement_quiz/PlacementQuiz.tscn",
	"tower_select": "res://scenes/campaign/tower_select/TowerSelect.tscn",
	"level":        "res://scenes/campaign/level/Level.tscn",
	"index":        "res://scenes/index/Index.tscn",
	"sandbox":      "res://scenes/sandbox/Sandbox.tscn",
	"leaderboard":  "res://scenes/leaderboard/Leaderboard.tscn",
	"analytics":    "res://scenes/analytics/Analytics.tscn",
	"settings":     "res://scenes/settings/Settings.tscn",

}

const LEVEL_CONFIGS = {
	1: {
		"name":        "Initialization",
		"concept":     "Arrays",
		"concept_desc":"Arrays store data at fixed indices. Your Array Tower accesses targets in O(1) time — instantly.",
		"enemy_tip":   "Basic packets only. Place towers near the inside of the S-curve for max coverage.",
		"waves":       3,
		"start_ram":   150,
		"tower_slots": 2,
		# S-curve: enter row 5, curve up to row 3, curve down to row 6, exit
		"waypoints": [
			Vector2(0, 320),
			Vector2(320, 320),
			Vector2(320, 192),
			Vector2(704, 192),
			Vector2(704, 384),
			Vector2(1088, 384),
		],
		"tower_spots": [
			Vector2i(3, 2), Vector2i(3, 6),
			Vector2i(5, 4), Vector2i(7, 4),
			Vector2i(9, 1), Vector2i(10, 5),
			Vector2i(14, 5), Vector2i(16, 5),
		],
		"required_towers": ["tower_array"],
		"towers": ["tower_array"],
		"enemy_types": ["basic_packet", "indexed_packet"],
	},
	2: {
		"name":        "Stack Overflow",
		"concept":     "Stacks",
		"concept_desc":"A Stack is LIFO — Last In First Out. Your Stack Tower targets the most recently arrived enemy first.",
		"enemy_tip":   "Indexed packets have damage resistance. Stack Tower's LIFO targeting helps pick them off.",
		"waves":       4,
		"start_ram":   175,
		"tower_slots": 3,
		# Staircase: enter row 2, drop to row 7, go right, rise to row 4, exit
		"waypoints": [
			Vector2(0, 128),
			Vector2(320, 128),
			Vector2(320, 448),
			Vector2(640, 448),
			Vector2(640, 256),
			Vector2(1088, 256),
		],
		"tower_spots": [
			Vector2i(2, 1), Vector2i(4, 1),
			Vector2i(2, 7), Vector2i(5, 7),
			Vector2i(7, 6), Vector2i(9, 6),
			Vector2i(11, 3), Vector2i(13, 3),
			Vector2i(15, 3), Vector2i(16, 5),
		],
		"required_towers": ["tower_array", "tower_stack"],
		"towers": ["tower_array", "tower_stack"],
		"enemy_types": ["basic_packet", "indexed_packet", "overflow_packet"],
	},
	3: {
		"name":        "Queue Protocol",
		"concept":     "Queues",
		"concept_desc":"A Queue is FIFO — First In First Out. Your Queue Tower targets the first enemy that entered its range, and pierces through to the one behind it.",
		"enemy_tip":   "Overflow packets grow stronger when enemies behind them die. Stack Tower's LIFO helps clear them.",
		"waves":       4,
		"start_ram":   200,
		"tower_slots": 3,
		# Zig-zag: 3 long horizontal passes across the grid
		"waypoints": [
			Vector2(0, 64),
			Vector2(256, 64),
			Vector2(256, 448),
			Vector2(576, 448),
			Vector2(576, 64),
			Vector2(896, 64),
			Vector2(896, 480),
			Vector2(1088, 480),
		],
		"tower_spots": [
			Vector2i(1, 0), Vector2i(3, 0),
			Vector2i(1, 6), Vector2i(3, 6),
			Vector2i(7, 6), Vector2i(9, 6),
			Vector2i(7, 0), Vector2i(11, 0),
			Vector2i(14, 0), Vector2i(15, 7),
		],
		"required_towers": ["tower_queue"],
		"towers": ["tower_array", "tower_stack", "tower_queue"],
		"enemy_types": ["basic_packet", "overflow_packet", "queue_jumper"],
	},
	4: {
		"name":        "Linked Assault",
		"concept":     "Linked Lists",
		"concept_desc":"A Linked List connects nodes with pointers. Your Linked Tower chains damage — hitting one enemy then jumping to the next nearby one.",
		"enemy_tip":   "Queue Jumper packets speed up when they reach the front. Queue Tower's FIFO targeting counters them.",
		"waves":       5,
		"start_ram":   200,
		"tower_slots": 3,
		# Snake: enter row 3, up to row 1, right, down to row 6, right, up to row 1, exit
		"waypoints": [
			Vector2(0, 192),
			Vector2(192, 192),
			Vector2(192, 64),
			Vector2(512, 64),
			Vector2(512, 384),
			Vector2(832, 384),
			Vector2(832, 128),
			Vector2(1088, 128),
		],
		"tower_spots": [
			Vector2i(1, 3), Vector2i(3, 3),
			Vector2i(4, 0), Vector2i(6, 0),
			Vector2i(4, 5), Vector2i(6, 5),
			Vector2i(10, 5), Vector2i(12, 5),
			Vector2i(14, 1), Vector2i(16, 1),
		],
		"required_towers": ["tower_linked_list"],
		"towers": ["tower_array", "tower_stack", "tower_queue", "tower_linked_list"],
		"enemy_types": ["basic_packet", "queue_jumper", "linked_drain"],
	},
	5: {
		"name":        "Bubble Protocol",
		"concept":     "Bubble Sort",
		"concept_desc":"Bubble Sort compares adjacent elements repeatedly — O(n²). Your Bubble Tower hits ALL enemies in range simultaneously, like comparing every pair.",
		"enemy_tip":   "Linked Drain packets share damage with a partner. Linked Tower's chain damage hits both at once!",
		"waves":       5,
		"start_ram":   225,
		"tower_slots": 4,
		# Switchback: enter row 7, up to row 1, right, back down to row 7, right, up to row 2, exit
		"waypoints": [
			Vector2(0, 448),
			Vector2(256, 448),
			Vector2(256, 64),
			Vector2(640, 64),
			Vector2(640, 448),
			Vector2(896, 448),
			Vector2(896, 128),
			Vector2(1088, 128),
		],
		"tower_spots": [
			Vector2i(1, 5), Vector2i(3, 5),
			Vector2i(1, 7), Vector2i(4, 7),
			Vector2i(6, 0), Vector2i(8, 0),
			Vector2i(6, 7), Vector2i(9, 6),
			Vector2i(13, 5), Vector2i(15, 1),
		],
		"required_towers": ["tower_bubble"],
		"towers": ["tower_array", "tower_stack", "tower_queue", "tower_linked_list", "tower_bubble"],
		"enemy_types": ["basic_packet", "linked_drain", "bubble_shield"],
	},
	6: {
		"name":        "Selection Strike",
		"concept":     "Selection Sort",
		"concept_desc":"Selection Sort finds the minimum element each pass. Your Selection Tower always targets the lowest HP enemy — finishing off the weakest first.",
		"enemy_tip":   "Bubble Shield packets absorb the first few hits. Bubble Tower's AoE pops their shields fast!",
		"waves":       5,
		"start_ram":   225,
		"tower_slots": 4,
		# Z-stair: enter row 1, drop to row 6, right, rise to row 2, exit
		"waypoints": [
			Vector2(0, 64),
			Vector2(384, 64),
			Vector2(384, 384),
			Vector2(768, 384),
			Vector2(768, 128),
			Vector2(1088, 128),
		],
		"tower_spots": [
			Vector2i(2, 0), Vector2i(4, 0),
			Vector2i(2, 5), Vector2i(5, 5),
			Vector2i(7, 6), Vector2i(9, 6),
			Vector2i(11, 5), Vector2i(13, 5),
			Vector2i(15, 1), Vector2i(16, 3),
		],
		"required_towers": ["tower_selection"],
		"towers": ["tower_array", "tower_stack", "tower_queue", "tower_bubble", "tower_selection"],
		"enemy_types": ["basic_packet", "bubble_shield", "selection_mark"],
	},
	7: {
		"name":        "Stack Defense",
		"concept":     "Insertion Sort",
		"concept_desc":"Insertion Sort inserts each element into its correct position one at a time. Your Insertion Tower applies stacking damage-over-time — inserting damage repeatedly.",
		"enemy_tip":   "Selection Mark packets are nearly invulnerable unless they're the lowest HP. Selection Tower auto-targets them!",
		"waves":       6,
		"start_ram":   250,
		"tower_slots": 4,
		# Multi-switchback: 4 vertical passes, tight turns
		"waypoints": [
			Vector2(0, 320),
			Vector2(192, 320),
			Vector2(192, 64),
			Vector2(448, 64),
			Vector2(448, 448),
			Vector2(704, 448),
			Vector2(704, 64),
			Vector2(960, 64),
			Vector2(960, 480),
			Vector2(1088, 480),
		],
		"tower_spots": [
			Vector2i(1, 5), Vector2i(3, 5),
			Vector2i(1, 1), Vector2i(4, 1),
			Vector2i(4, 7), Vector2i(6, 7),
			Vector2i(8, 6), Vector2i(10, 6),
			Vector2i(12, 1), Vector2i(15, 1),
			Vector2i(15, 7), Vector2i(17, 7),
		],
		"required_towers": ["tower_insertion"],
		"towers": ["tower_array", "tower_stack", "tower_queue", "tower_linked_list", "tower_bubble", "tower_selection", "tower_insertion"],
		"enemy_types": ["basic_packet", "selection_mark", "insertion_stack"],
	},
	8: {
		"name":        "Quick Strike",
		"concept":     "Quick Sort",
		"concept_desc":"Quick Sort divides around a pivot. Your Quick Tower splits its shot — hitting 2 enemies simultaneously like dividing the array into left and right partitions.",
		"enemy_tip":   "Insertion Stack packets take extra damage-over-time. Insertion Tower's DoT shreds them! Pivot Splitter boss divides on death.",
		"waves":       6,
		"start_ram":   250,
		"tower_slots": 4,
		# Cascade: enter row 2, drop to row 6, rise to row 1, drop to row 6, exit
		"waypoints": [
			Vector2(0, 128),
			Vector2(256, 128),
			Vector2(256, 384),
			Vector2(576, 384),
			Vector2(576, 64),
			Vector2(832, 64),
			Vector2(832, 384),
			Vector2(1088, 384),
		],
		"tower_spots": [
			Vector2i(1, 2), Vector2i(3, 2),
			Vector2i(1, 6), Vector2i(4, 6),
			Vector2i(6, 5), Vector2i(8, 5),
			Vector2i(10, 1), Vector2i(12, 1),
			Vector2i(14, 5), Vector2i(16, 5),
		],
		"required_towers": ["tower_quick"],
		"towers": ["tower_array", "tower_stack", "tower_queue", "tower_linked_list", "tower_bubble", "tower_selection", "tower_insertion", "tower_quick"],
		"enemy_types": ["basic_packet", "insertion_stack", "pivot_splitter"],
	},
	9: {
		"name":        "Merge Protocol",
		"concept":     "Merge Sort",
		"concept_desc":"Merge Sort splits arrays in half then merges sorted halves. Your Merge Tower does guaranteed AoE damage — O(n log n) means no enemy escapes.",
		"enemy_tip":   "Pivot Splitter boss divides in two on death. Quick Tower's split shot counters the split!",
		"waves":       6,
		"start_ram":   275,
		"tower_slots": 5,
		# Loop-back: enter row 7, rise to row 1, right, back down to row 5, left, down to row 7, exit
		"waypoints": [
			Vector2(0, 448),
			Vector2(384, 448),
			Vector2(384, 64),
			Vector2(768, 64),
			Vector2(768, 320),
			Vector2(576, 320),
			Vector2(576, 448),
			Vector2(1088, 448),
		],
		"tower_spots": [
			Vector2i(2, 5), Vector2i(4, 5),
			Vector2i(2, 1), Vector2i(5, 1),
			Vector2i(9, 1), Vector2i(11, 1),
			Vector2i(10, 5), Vector2i(12, 5),
			Vector2i(7, 4), Vector2i(16, 7),
		],
		"required_towers": ["tower_merge"],
		"towers": ["tower_array", "tower_stack", "tower_queue", "tower_linked_list", "tower_bubble", "tower_selection", "tower_insertion", "tower_quick", "tower_merge"],
		"enemy_types": ["basic_packet", "pivot_splitter", "merge_twin"],
	},
	10: {
		"name":        "Count Down",
		"concept":     "Counting Sort",
		"concept_desc":"Counting Sort counts occurrences of each value. Your Count Tower gets stronger the more enemies are in range — O(n+k) means it scales with crowd size.",
		"enemy_tip":   "Merge Twin packets absorb their partner's HP when one dies. Merge Tower's AoE kills both evenly!",
		"waves":       7,
		"start_ram":   275,
		"tower_slots": 5,
		# Serpentine: 4 horizontal passes (rows 1→7→1→7→1), tight S-bends
		"waypoints": [
			Vector2(0, 64),
			Vector2(192, 64),
			Vector2(192, 448),
			Vector2(448, 448),
			Vector2(448, 64),
			Vector2(704, 64),
			Vector2(704, 448),
			Vector2(960, 448),
			Vector2(960, 64),
			Vector2(1088, 64),
		],
		"tower_spots": [
			Vector2i(1, 0), Vector2i(3, 0),
			Vector2i(1, 6), Vector2i(3, 6),
			Vector2i(6, 0), Vector2i(6, 6),
			Vector2i(9, 0), Vector2i(9, 6),
			Vector2i(13, 0), Vector2i(15, 0),
		],
		"required_towers": ["tower_counting"],
		"towers": ["tower_array", "tower_stack", "tower_queue", "tower_bubble", "tower_selection", "tower_insertion", "tower_quick", "tower_merge", "tower_counting"],
		"enemy_types": ["basic_packet", "merge_twin", "count_meter"],
	},
	11: {
		"name":        "Radix Rush",
		"concept":     "Radix Sort",
		"concept_desc":"Radix Sort processes digits one at a time. Your Radix Tower fires rapid multi-pass bursts — hitting every enemy multiple times like sorting digit by digit.",
		"enemy_tip":   "Count Meter packets resist damage until their counter fills. Count Tower's rapid hits fill the counter fast!",
		"waves":       7,
		"start_ram":   275,
		"tower_slots": 5,
		# Complex cascade: enter row 4, up to row 1, down to row 6, up to row 2, down to row 6, exit
		"waypoints": [
			Vector2(0, 256),
			Vector2(192, 256),
			Vector2(192, 64),
			Vector2(448, 64),
			Vector2(448, 384),
			Vector2(640, 384),
			Vector2(640, 128),
			Vector2(832, 128),
			Vector2(832, 384),
			Vector2(1088, 384),
		],
		"tower_spots": [
			Vector2i(1, 4), Vector2i(3, 4),
			Vector2i(4, 1), Vector2i(6, 1),
			Vector2i(6, 6), Vector2i(4, 6),
			Vector2i(10, 4), Vector2i(9, 2),
			Vector2i(12, 2), Vector2i(14, 6),
		],
		"required_towers": ["tower_radix"],
		"towers": ["tower_array", "tower_stack", "tower_queue", "tower_linked_list", "tower_bubble", "tower_selection", "tower_insertion", "tower_quick", "tower_merge", "tower_counting", "tower_radix"],
		"enemy_types": ["basic_packet", "count_meter", "radix_digit"],
	},
	12: {
		"name":        "Linear Sweep",
		"concept":     "Linear Search",
		"concept_desc":"Linear Search checks every element one by one. Your Linear Tower scans ALL enemies in a wide range — it never misses but takes time like O(n) sequential checking.",
		"enemy_tip":   "Radix Digit packets have 3 health segments. Radix Tower's multi-pass strips them digit by digit!",
		"waves":       7,
		"start_ram":   300,
		"tower_slots": 5,
		# Long meander: 5 passes (rows 2→7→2→7→2), maximum grid coverage
		"waypoints": [
			Vector2(0, 128),
			Vector2(256, 128),
			Vector2(256, 448),
			Vector2(512, 448),
			Vector2(512, 128),
			Vector2(768, 128),
			Vector2(768, 448),
			Vector2(1024, 448),
			Vector2(1024, 128),
			Vector2(1088, 128),
		],
		"tower_spots": [
			Vector2i(1, 2), Vector2i(3, 2),
			Vector2i(1, 7), Vector2i(4, 7),
			Vector2i(6, 2), Vector2i(8, 2),
			Vector2i(6, 7), Vector2i(10, 7),
			Vector2i(13, 2), Vector2i(15, 2),
		],
		"required_towers": ["tower_linear"],
		"towers": ["tower_array", "tower_stack", "tower_queue", "tower_linked_list", "tower_bubble", "tower_selection", "tower_insertion", "tower_quick", "tower_merge", "tower_counting", "tower_radix", "tower_linear"],
		"enemy_types": ["basic_packet", "radix_digit", "scan_wave"],
	},
	13: {
		"name":        "Binary Endgame",
		"concept":     "Binary Search",
		"concept_desc":"Binary Search finds targets in O(log n) by halving the search space. Your Binary Tower is a precision sniper — it instantly locates and destroys the highest-priority target.",
		"enemy_tip":   "Scan Wave packets are immune mid-sweep. Binary Mask alternates vulnerable halves. Binary Tower's precision beats both!",
		"waves":       8,
		"start_ram":   300,
		"tower_slots": 6,
		# Tight switchbacks: enter row 4, up to row 1, down to row 6, up to row 1, down to row 6, exit
		"waypoints": [
			Vector2(0, 256),
			Vector2(192, 256),
			Vector2(192, 64),
			Vector2(448, 64),
			Vector2(448, 384),
			Vector2(704, 384),
			Vector2(704, 64),
			Vector2(960, 64),
			Vector2(960, 384),
			Vector2(1088, 384),
		],
		"tower_spots": [
			Vector2i(1, 3), Vector2i(3, 3),
			Vector2i(4, 1), Vector2i(6, 1),
			Vector2i(4, 6), Vector2i(6, 6),
			Vector2i(8, 5), Vector2i(10, 5),
			Vector2i(12, 1), Vector2i(14, 1),
			Vector2i(15, 6), Vector2i(17, 6),
		],
		"required_towers": ["tower_binary"],
		"towers": ["tower_array", "tower_stack", "tower_queue", "tower_linked_list", "tower_bubble", "tower_selection", "tower_insertion", "tower_quick", "tower_merge", "tower_counting", "tower_radix", "tower_linear", "tower_binary"],
		"enemy_types": ["basic_packet", "scan_wave", "binary_mask"],
	},
}

const TOWER_DEFINITIONS = {
	"tower_array": {
		"tower_id":    "tower_array",
		"tower_name":  "Array Tower",
		"description": "Fast attack. O(1) access speed.",
		"data_structure": "Array",
		"ram_cost":    50,
		"damage":      18.0,
		"attack_speed":2.0,
		"attack_range":140.0,
		"time_complexity": "O(1)",
		"color":       Color("#00D4FF"),
		"icon_text":   "[ ]",
	},
	"tower_stack": {
		"tower_id":    "tower_stack",
		"tower_name":  "Stack Tower",
		"description": "Hits the most recent enemy. LIFO targeting.",
		"data_structure": "Stack",
		"ram_cost":    75,
		"damage":      28.0,
		"attack_speed":1.2,
		"attack_range":130.0,
		"time_complexity": "O(1)",
		"color":       Color("#FF6B35"),
		"icon_text":   "↑↓",
	},
	"tower_queue": {
		"tower_id":    "tower_queue",
		"tower_name":  "Queue Tower",
		"description": "Pierces 2 enemies in line. FIFO targeting.",
		"data_structure": "Queue",
		"ram_cost":    75,
		"damage":      22.0,
		"attack_speed":1.6,
		"attack_range":160.0,
		"time_complexity": "O(1)",
		"color":       Color("#9B59B6"),
		"icon_text":   "→",
	},
	"tower_linked_list": {
		"tower_id":    "tower_linked_list",
		"tower_name":  "Linked Tower",
		"description": "Chain damage across 3 nearby enemies.",
		"data_structure": "Linked List",
		"ram_cost":    100,
		"damage":      20.0,
		"attack_speed":1.3,
		"attack_range":150.0,
		"time_complexity": "O(n)",
		"color":       Color("#00FF88"),
		"icon_text":   "→→",
	},
	"tower_bubble": {
		"tower_id":    "tower_bubble",
		"tower_name":  "Bubble Tower",
		"description": "AoE pulse — damages every enemy in range.",
		"data_structure": "Bubble Sort",
		"ram_cost":    90,
		"damage":      16.0,
		"attack_speed":1.5,
		"attack_range":130.0,
		"time_complexity": "O(n²)",
		"color":       Color("#FFB800"),
		"icon_text":   "↑↑",
	},
	"tower_selection": {
		"tower_id":    "tower_selection",
		"tower_name":  "Selection Tower",
		"description": "Always finishes off the weakest enemy.",
		"data_structure": "Selection Sort",
		"ram_cost":    110,
		"damage":      24.0,
		"attack_speed":1.0,
		"attack_range":170.0,
		"time_complexity": "O(n²)",
		"color":       Color("#E74C3C"),
		"icon_text":   "→↓",
	},
	"tower_insertion": {
		"tower_id":    "tower_insertion",
		"tower_name":  "Insertion Tower",
		"description": "Applies stacking damage-over-time.",
		"data_structure": "Insertion Sort",
		"ram_cost":    120,
		"damage":      18.0,
		"attack_speed":1.4,
		"attack_range":140.0,
		"time_complexity": "O(n)",
		"color":       Color("#1ABC9C"),
		"icon_text":   "←↑",
	},
}

# Currently selected level
var current_level: int = 1
var current_scene_key: String = ""
var current_sandbox_structure: String = ""

func _ready() -> void:
	SignalBus.scene_change_requested.connect(_on_scene_change_requested)

func go_to(scene_key: String) -> void:
	if not SCENES.has(scene_key):
		push_error("[GameManager] Unknown scene key: " + scene_key)
		return
	current_scene_key = scene_key
	SoundManager.play_transition()
	get_tree().change_scene_to_file(SCENES[scene_key])

func _on_scene_change_requested(scene_path: String) -> void:
	get_tree().change_scene_to_file(scene_path)

func quit_game() -> void:
	get_tree().quit()
