# GameManager.gd
extends Node

# Add these variables to GameManager.gd:
var selected_towers: Array = []


# Add tower_select to your scene map:
const SCENES = {
	"login":        "res://scenes/login/Login.tscn",
	"main_menu":    "res://scenes/main_menu/MainMenu.tscn",
	"academy":      "res://scenes/academy/Academy.tscn",
	"campaign":     "res://scenes/campaign/level_select/LevelSelect.tscn",
	"tower_select": "res://scenes/campaign/tower_select/TowerSelect.tscn",
	"level":        "res://scenes/campaign/level/Level.tscn",
	"index":        "res://scenes/index/Index.tscn",
	"sandbox":      "res://scenes/sandbox/Sandbox.tscn",
	"leaderboard":  "res://scenes/leaderboard/Leaderboard.tscn",
	"analytics":    "res://scenes/analytics/Analytics.tscn",
	"settings":     "res://scenes/settings/Settings.tscn",
	"placement_quiz": "res://scenes/placement_quiz/PlacementQuiz.tscn",
}

const LEVEL_CONFIGS = {
	1: {
		"name":        "Initialization",
		"concept":     "Arrays",
		"concept_desc":"Arrays store data at fixed indices. Your Array Tower accesses targets in O(1) time — instantly.",
		"enemy_tip":   "Basic packets only. Place towers near the middle of the path.",
		"waves":       3,
		"start_ram":   150,
		"tower_slots": 2,
		"waypoints": [
			Vector2(0, 320), Vector2(1152, 320)
		],
		"tower_spots": [
			Vector2i(2, 3), Vector2i(2, 6),
			Vector2i(6, 3), Vector2i(6, 6),
			Vector2i(10, 3), Vector2i(10, 6),
			Vector2i(14, 3), Vector2i(14, 6),
		],
		"required_towers": ["tower_array"],
		"towers": ["tower_array"],
	},
	2: {
		"name":        "Stack Overflow",
		"concept":     "Stacks",
		"concept_desc":"A Stack is LIFO — Last In First Out. Your Stack Tower targets the most recently arrived enemy first.",
		"enemy_tip":   "Fast packets appear in wave 3. Stack Tower hits them hard.",
		"waves":       4,
		"start_ram":   175,
		"tower_slots": 3,
		"waypoints": [
			Vector2(0, 160),
			Vector2(576, 160),
			Vector2(576, 480),
			Vector2(1152, 480),
		],
		"tower_spots": [
			Vector2i(2, 1), Vector2i(5, 1),
			Vector2i(2, 4), Vector2i(5, 4),
			Vector2i(8, 4), Vector2i(11, 4),
			Vector2i(8, 7), Vector2i(11, 7),
			Vector2i(14, 7), Vector2i(16, 7),
		],
		"required_towers": ["tower_array", "tower_stack"],
		"towers": ["tower_array", "tower_stack"],
	},
	3: {
		"name":        "Queue Protocol",
		"concept":     "Queues",
		"concept_desc":"A Queue is FIFO — First In First Out. Your Queue Tower targets the first enemy that entered its range, and pierces through to the one behind it.",
		"enemy_tip":   "Fast packets arrive early. Queue Tower's pierce ability is essential here.",
		"waves":       4,
		"start_ram":   200,
		"tower_slots": 3,
		"waypoints": [
			Vector2(0, 96),
			Vector2(384, 96),
			Vector2(384, 480),
			Vector2(768, 480),
			Vector2(768, 224),
			Vector2(1152, 224),
		],
		"tower_spots": [
			Vector2i(1, 1), Vector2i(4, 1),
			Vector2i(1, 5), Vector2i(4, 5),
			Vector2i(7, 5), Vector2i(10, 5),
			Vector2i(7, 2), Vector2i(10, 2),
			Vector2i(13, 2), Vector2i(16, 2),
		],
		"required_towers": ["tower_queue"],
		"towers": ["tower_array", "tower_stack", "tower_queue"],
	},
	4: {
		"name":        "Linked Assault",
		"concept":     "Linked Lists",
		"concept_desc":"A Linked List connects nodes with pointers. Your Linked Tower chains damage — hitting one enemy then jumping to the next nearby one.",
		"enemy_tip":   "Heavy packets appear. Linked Tower's chain damage is ideal for clustered enemies.",
		"waves":       5,
		"start_ram":   200,
		"tower_slots": 3,
		"waypoints": [
			Vector2(0, 224),
			Vector2(256, 224),
			Vector2(256, 96),
			Vector2(640, 96),
			Vector2(640, 416),
			Vector2(896, 416),
			Vector2(896, 224),
			Vector2(1152, 224),
		],
		"tower_spots": [
			Vector2i(1, 2), Vector2i(1, 5),
			Vector2i(3, 1), Vector2i(6, 1),
			Vector2i(9, 1), Vector2i(12, 1),
			Vector2i(9, 5), Vector2i(12, 5),
			Vector2i(15, 2), Vector2i(15, 5),
		],
		"required_towers": ["tower_linked_list"],
		"towers": ["tower_array", "tower_stack", "tower_queue", "tower_linked_list"],
	},
	5: {
		"name":        "Bubble Protocol",
		"concept":     "Bubble Sort",
		"concept_desc":"Bubble Sort compares adjacent elements repeatedly — O(n²). Your Bubble Tower hits ALL enemies in range simultaneously, like comparing every pair.",
		"enemy_tip":   "Encrypted packets resist single-target damage. Bubble Tower's AoE is essential.",
		"waves":       5,
		"start_ram":   225,
		"tower_slots": 4,
		"waypoints": [
			Vector2(0, 480),
			Vector2(320, 480),
			Vector2(320, 160),
			Vector2(832, 160),
			Vector2(832, 352),
			Vector2(512, 352),
			Vector2(512, 480),
			Vector2(1152, 480),
		],
		"tower_spots": [
			Vector2i(1, 6), Vector2i(4, 6),
			Vector2i(1, 2), Vector2i(4, 2),
			Vector2i(7, 2), Vector2i(11, 2),
			Vector2i(7, 5), Vector2i(11, 5),
			Vector2i(14, 6), Vector2i(16, 6),
		],
		"required_towers": ["tower_bubble"],
		"towers": ["tower_array", "tower_stack", "tower_queue", "tower_linked_list", "tower_bubble"],
	},
	6: {
		"name":        "Selection Strike",
		"concept":     "Selection Sort",
		"concept_desc":"Selection Sort finds the minimum element each pass. Your Selection Tower always targets the lowest HP enemy — finishing off the weakest first.",
		"enemy_tip":   "Stealth packets are hard to see. Selection Tower always finds and targets them regardless.",
		"waves":       5,
		"start_ram":   225,
		"tower_slots": 4,
		"waypoints": [
			Vector2(0, 96),
			Vector2(1152, 96),
			Vector2(1152, 320),
			Vector2(0, 320),
			Vector2(0, 480),
			Vector2(1152, 480),
		],
		"tower_spots": [
			Vector2i(2, 2), Vector2i(5, 2),
			Vector2i(8, 2), Vector2i(11, 2),
			Vector2i(14, 2), Vector2i(16, 2),
			Vector2i(2, 5), Vector2i(5, 5),
			Vector2i(8, 5), Vector2i(11, 5),
		],
		"required_towers": ["tower_selection"],
		"towers": ["tower_array", "tower_stack", "tower_queue", "tower_bubble", "tower_selection"],
	},
	7: {
		"name":        "Stack Defense",
		"concept":     "Insertion Sort",
		"concept_desc":"Insertion Sort inserts each element into its correct position one at a time. Your Insertion Tower applies stacking damage-over-time — inserting damage repeatedly.",
		"enemy_tip":   "Heavy and encrypted packets. Insertion Tower's DoT stacks up on high-HP enemies.",
		"waves":       6,
		"start_ram":   250,
		"tower_slots": 4,
		"waypoints": [
			Vector2(0, 320),
			Vector2(192, 320),
			Vector2(192, 96),
			Vector2(448, 96),
			Vector2(448, 416),
			Vector2(704, 416),
			Vector2(704, 160),
			Vector2(960, 160),
			Vector2(960, 480),
			Vector2(1152, 480),
		],
		"tower_spots": [
			Vector2i(1, 1), Vector2i(1, 5),
			Vector2i(4, 1), Vector2i(4, 5),
			Vector2i(8, 1), Vector2i(8, 6),
			Vector2i(12, 1), Vector2i(12, 6),
			Vector2i(16, 1), Vector2i(16, 6),
		],
		"required_towers": ["tower_insertion"],
		"towers": ["tower_array", "tower_stack", "tower_queue", "tower_linked_list", "tower_bubble", "tower_selection", "tower_insertion"],
	},
	8: {
		"name":        "Quick Strike",
		"concept":     "Quick Sort",
		"concept_desc":"Quick Sort divides around a pivot. Your Quick Tower splits its shot — hitting 2 enemies simultaneously like dividing the array into left and right partitions.",
		"enemy_tip":   "Boss packet appears in wave 5. Quick Tower's split shot is essential for the boss split.",
		"waves":       6,
		"start_ram":   250,
		"tower_slots": 4,
		"waypoints": [
			Vector2(0, 160),
			Vector2(384, 160),
			Vector2(384, 416),
			Vector2(768, 416),
			Vector2(768, 96),
			Vector2(1152, 96),
		],
		"tower_spots": [
			Vector2i(1, 1), Vector2i(1, 4),
			Vector2i(4, 1), Vector2i(4, 4),
			Vector2i(7, 4), Vector2i(7, 7),
			Vector2i(10, 4), Vector2i(10, 7),
			Vector2i(13, 1), Vector2i(16, 1),
		],
		"required_towers": ["tower_quick"],
		"towers": ["tower_array", "tower_stack", "tower_queue", "tower_linked_list", "tower_bubble", "tower_selection", "tower_insertion", "tower_quick"],
	},
	9: {
		"name":        "Merge Protocol",
		"concept":     "Merge Sort",
		"concept_desc":"Merge Sort splits arrays in half then merges sorted halves. Your Merge Tower does guaranteed AoE damage — O(n log n) means no enemy escapes.",
		"enemy_tip":   "Boss + stealth combination. Merge Tower's AoE hits all enemies including stealth.",
		"waves":       6,
		"start_ram":   275,
		"tower_slots": 5,
		"waypoints": [
			Vector2(0, 480),
			Vector2(576, 480),
			Vector2(576, 96),
			Vector2(1152, 96),
			Vector2(1152, 320),
			Vector2(768, 320),
			Vector2(768, 480),
		],
		"tower_spots": [
			Vector2i(1, 6), Vector2i(4, 6),
			Vector2i(7, 6), Vector2i(7, 1),
			Vector2i(10, 1), Vector2i(13, 1),
			Vector2i(16, 1), Vector2i(16, 4),
			Vector2i(13, 4), Vector2i(10, 6),
		],
		"required_towers": ["tower_merge"],
		"towers": ["tower_array", "tower_stack", "tower_queue", "tower_linked_list", "tower_bubble", "tower_selection", "tower_insertion", "tower_quick", "tower_merge"],
	},
	10: {
		"name":        "Count Down",
		"concept":     "Counting Sort",
		"concept_desc":"Counting Sort counts occurrences of each value. Your Count Tower gets stronger the more enemies are in range — O(n+k) means it scales with crowd size.",
		"enemy_tip":   "Large waves with mixed enemies. Count Tower excels when many enemies cluster together.",
		"waves":       7,
		"start_ram":   275,
		"tower_slots": 5,
		"waypoints": [
			Vector2(0, 96),
			Vector2(256, 96),
			Vector2(256, 480),
			Vector2(512, 480),
			Vector2(512, 96),
			Vector2(768, 96),
			Vector2(768, 480),
			Vector2(1024, 480),
			Vector2(1024, 96),
			Vector2(1152, 96),
		],
		"tower_spots": [
			Vector2i(1, 1), Vector2i(1, 6),
			Vector2i(3, 1), Vector2i(3, 6),
			Vector2i(6, 1), Vector2i(6, 6),
			Vector2i(9, 1), Vector2i(9, 6),
			Vector2i(12, 1), Vector2i(12, 6),
		],
		"required_towers": ["tower_counting"],
		"towers": ["tower_array", "tower_stack", "tower_queue", "tower_bubble", "tower_selection", "tower_insertion", "tower_quick", "tower_merge", "tower_counting"],
	},
	11: {
		"name":        "Radix Rush",
		"concept":     "Radix Sort",
		"concept_desc":"Radix Sort processes digits one at a time. Your Radix Tower fires rapid multi-pass bursts — hitting every enemy multiple times like sorting digit by digit.",
		"enemy_tip":   "Boss packet + encrypted combination. Radix Tower's rapid fire strips through armor.",
		"waves":       7,
		"start_ram":   275,
		"tower_slots": 5,
		"waypoints": [
			Vector2(0, 256),
			Vector2(192, 256),
			Vector2(192, 96),
			Vector2(576, 96),
			Vector2(576, 416),
			Vector2(384, 416),
			Vector2(384, 256),
			Vector2(768, 256),
			Vector2(768, 96),
			Vector2(1152, 96),
		],
		"tower_spots": [
			Vector2i(1, 3), Vector2i(1, 6),
			Vector2i(4, 1), Vector2i(7, 1),
			Vector2i(10, 1), Vector2i(10, 5),
			Vector2i(7, 5), Vector2i(4, 5),
			Vector2i(13, 1), Vector2i(16, 1),
		],
		"required_towers": ["tower_radix"],
		"towers": ["tower_array", "tower_stack", "tower_queue", "tower_linked_list", "tower_bubble", "tower_selection", "tower_insertion", "tower_quick", "tower_merge", "tower_counting", "tower_radix"],
	},
	12: {
		"name":        "Linear Sweep",
		"concept":     "Linear Search",
		"concept_desc":"Linear Search checks every element one by one. Your Linear Tower scans ALL enemies in a wide range — it never misses but takes time like O(n) sequential checking.",
		"enemy_tip":   "Stealth and encrypted mixed. Linear Tower's guaranteed scan hits even stealth packets.",
		"waves":       7,
		"start_ram":   300,
		"tower_slots": 5,
		"waypoints": [
			Vector2(0, 160),
			Vector2(288, 160),
			Vector2(288, 480),
			Vector2(576, 480),
			Vector2(576, 160),
			Vector2(864, 160),
			Vector2(864, 480),
			Vector2(1152, 480),
		],
		"tower_spots": [
			Vector2i(1, 1), Vector2i(1, 6),
			Vector2i(3, 1), Vector2i(3, 6),
			Vector2i(7, 1), Vector2i(7, 6),
			Vector2i(11, 1), Vector2i(11, 6),
			Vector2i(15, 1), Vector2i(15, 6),
		],
		"required_towers": ["tower_linear"],
		"towers": ["tower_array", "tower_stack", "tower_queue", "tower_linked_list", "tower_bubble", "tower_selection", "tower_insertion", "tower_quick", "tower_merge", "tower_counting", "tower_radix", "tower_linear"],
	},
	13: {
		"name":        "Binary Endgame",
		"concept":     "Binary Search",
		"concept_desc":"Binary Search finds targets in O(log n) by halving the search space. Your Binary Tower is a precision sniper — it instantly locates and destroys the highest-priority target.",
		"enemy_tip":   "All enemy types. Binary Tower one-shots most enemies. Use it wisely — slow attack speed.",
		"waves":       8,
		"start_ram":   300,
		"tower_slots": 6,
		"waypoints": [
			Vector2(0, 256),
			Vector2(192, 256),
			Vector2(192, 96),
			Vector2(576, 96),
			Vector2(576, 416),
			Vector2(384, 416),
			Vector2(384, 256),
			Vector2(768, 256),
			Vector2(768, 96),
			Vector2(1152, 96),
		],
		"tower_spots": [
			Vector2i(1, 3), Vector2i(1, 6),
			Vector2i(4, 1), Vector2i(4, 5),
			Vector2i(7, 1), Vector2i(7, 5),
			Vector2i(10, 1), Vector2i(10, 5),
			Vector2i(13, 1), Vector2i(13, 5),
			Vector2i(16, 1), Vector2i(16, 5),
		],
		"required_towers": ["tower_binary"],
		"towers": ["tower_array", "tower_stack", "tower_queue", "tower_linked_list", "tower_bubble", "tower_selection", "tower_insertion", "tower_quick", "tower_merge", "tower_counting", "tower_radix", "tower_linear", "tower_binary"],
	},
}

const TOWER_DEFINITIONS = {
	"tower_array": {
		"tower_id":    "tower_array",
		"tower_name":  "Array Tower",
		"description": "Fast attack. O(1) access speed.",
		"data_structure": "Array",
		"ram_cost":    50,
		"damage":      18.0,
		"attack_speed":2.0,
		"attack_range":140.0,
		"time_complexity": "O(1)",
		"color":       Color("#00D4FF"),
		"icon_text":   "[ ]",
	},
	"tower_stack": {
		"tower_id":    "tower_stack",
		"tower_name":  "Stack Tower",
		"description": "Hits the most recent enemy. LIFO targeting.",
		"data_structure": "Stack",
		"ram_cost":    75,
		"damage":      28.0,
		"attack_speed":1.2,
		"attack_range":130.0,
		"time_complexity": "O(1)",
		"color":       Color("#FF6B35"),
		"icon_text":   "↑↓",
	},
	"tower_queue": {
		"tower_id":    "tower_queue",
		"tower_name":  "Queue Tower",
		"description": "Pierces 2 enemies in line. FIFO targeting.",
		"data_structure": "Queue",
		"ram_cost":    75,
		"damage":      22.0,
		"attack_speed":1.6,
		"attack_range":160.0,
		"time_complexity": "O(1)",
		"color":       Color("#9B59B6"),
		"icon_text":   "→",
	},
	"tower_linked_list": {
		"tower_id":    "tower_linked_list",
		"tower_name":  "Linked Tower",
		"description": "Chain damage across 3 nearby enemies.",
		"data_structure": "Linked List",
		"ram_cost":    100,
		"damage":      20.0,
		"attack_speed":1.3,
		"attack_range":150.0,
		"time_complexity": "O(n)",
		"color":       Color("#00FF88"),
		"icon_text":   "→→",
	},
	"tower_bubble": {
		"tower_id":    "tower_bubble",
		"tower_name":  "Bubble Tower",
		"description": "AoE pulse — damages every enemy in range.",
		"data_structure": "Bubble Sort",
		"ram_cost":    90,
		"damage":      16.0,
		"attack_speed":1.5,
		"attack_range":130.0,
		"time_complexity": "O(n²)",
		"color":       Color("#FFB800"),
		"icon_text":   "↑↑",
	},
	"tower_selection": {
		"tower_id":    "tower_selection",
		"tower_name":  "Selection Tower",
		"description": "Always finishes off the weakest enemy.",
		"data_structure": "Selection Sort",
		"ram_cost":    110,
		"damage":      24.0,
		"attack_speed":1.0,
		"attack_range":170.0,
		"time_complexity": "O(n²)",
		"color":       Color("#E74C3C"),
		"icon_text":   "→↓",
	},
	"tower_insertion": {
		"tower_id":    "tower_insertion",
		"tower_name":  "Insertion Tower",
		"description": "Applies stacking damage-over-time.",
		"data_structure": "Insertion Sort",
		"ram_cost":    120,
		"damage":      18.0,
		"attack_speed":1.4,
		"attack_range":140.0,
		"time_complexity": "O(n)",
		"color":       Color("#1ABC9C"),
		"icon_text":   "←↑",
	},
}

# Currently selected level
var current_level: int = 1
var current_scene_key: String = ""
var current_sandbox_structure: String = ""


func _ready() -> void:
	SignalBus.scene_change_requested.connect(_on_scene_change_requested)

func go_to(scene_key: String) -> void:
	if not SCENES.has(scene_key):
		push_error("[GameManager] Unknown scene key: " + scene_key)
		return
	current_scene_key = scene_key
	get_tree().change_scene_to_file(SCENES[scene_key])
	print("[GameManager] Navigating to: ", scene_key)

func _on_scene_change_requested(scene_path: String) -> void:
	get_tree().change_scene_to_file(scene_path)

func quit_game() -> void:
	get_tree().quit()
